[plugins]
codecov = "org.enginehub.codecov:0.2.0"

[versions]
worldedit = "7.4.0-SNAPSHOT"
worldguard = "7.0.10"

# Minimum versions we apply to make dependencies support newer Java
minimumAsm = "9.7"
minimumJdependency = "2.10"
minimumTinyRemapper = "0.8.11"

lang-version = "1604"

[libraries]

levelHeadered = "net.octyl.level-headered:plugin:0.1.1"
grgit = "org.ajoberstar.grgit:grgit-gradle:5.2.2"
shadow = "com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:8.3.9"
jfrog-buildinfo = "org.jfrog.buildinfo:build-info-extractor-gradle:5.2.0"

paperweight = "io.papermc.paperweight.userdev:io.papermc.paperweight.userdev.gradle.plugin:1.7.1"

squirrelid = "org.enginehub:squirrelid:0.3.2"

autoService = "com.google.auto.service:auto-service:1.1.1"

jspecify = "org.jspecify:jspecify:0.3.0"
jetbrains-annotations = "org.jetbrains:annotations:24.1.0"

junit-bom = "org.junit:junit-bom:6.0.1"
junit-jupiter-api.module = "org.junit.jupiter:junit-jupiter-api"
junit-jupiter-params.module = "org.junit.jupiter:junit-jupiter-params"
junit-jupiter-engine.module = "org.junit.jupiter:junit-jupiter-engine"
junit-platform-launcher.module = "org.junit.platform:junit-platform-launcher"

mockito-bom = "org.mockito:mockito-bom:5.11.0"
mockito-core.module = "org.mockito:mockito-core"
mockito-junit-jupiter.module = "org.mockito:mockito-junit-jupiter"

paperApi = "io.papermc.paper:paper-api:1.21.10-R0.1-SNAPSHOT"
vaultApi = "com.github.MilkBowl:VaultAPI:1.7.1"

dummypermscompat = "com.sk89q:dummypermscompat:1.10"
bstats-bukkit = "org.bstats:bstats-bukkit:3.1.0"

# Also update in build-logic/src/main/kotlin/buildlogic.platform.gradle.kts
flyway-core = "org.flywaydb:flyway-core:3.0"

hamcrest-library = "org.hamcrest:hamcrest-library:2.2"

adventure = "net.kyori:adventure-api:4.20.0"
adventureMinimessage = "net.kyori:adventure-text-minimessage:4.20.0"
adventureGson = "net.kyori:adventure-text-serializer-gson:4.20.0"
adventurePlain = "net.kyori:adventure-text-serializer-plain:4.20.0"

# Mojang-provided libraries, CHECK AGAINST MINECRAFT for versions
guava = "com.google.guava:guava:33.5.0-jre!!"
log4j-bom = "org.apache.logging.log4j:log4j-bom:2.24.1!!"
log4j-api.module = "org.apache.logging.log4j:log4j-api"
log4j-core.module = "org.apache.logging.log4j:log4j-core"
gson = "com.google.code.gson:gson:2.13.2!!"
fastutil = "it.unimi.dsi:fastutil:8.5.18!!"

# Bukkit-provided libraries, CHECK AGAINST SPIGOT for versions
# Note that we need to balance support for older MC versus working at all on newer ones, so the exact versions here
# may not be the same as the ones in the latest Bukkit API.
snakeyaml = "org.yaml:snakeyaml:2.0"

[libraries.worldedit-core]
module = "com.sk89q.worldedit:worldedit-core"
version.ref = "worldedit"

[libraries.worldedit-bukkit]
module = "com.sk89q.worldedit:worldedit-bukkit"
version.ref = "worldedit"

[libraries.worldedit-libs-ap]
module = "com.sk89q.worldedit.worldedit-libs:ap"
version.ref = "worldedit"

[libraries.worldguard-core]
module = "com.sk89q.worldguard:worldguard-core"
version.ref = "worldguard"

[libraries.worldguard-bukkit]
module = "com.sk89q.worldguard:worldguard-bukkit"
version.ref = "worldguard"
