# CraftBook Configuration for Bukkit. Generated for version: 5.0.0-SNAPSHOT;838050c
# This configuration will automatically add new configuration options for you,
# So there is no need to regenerate this configuration unless you need to.
# More information about these features are available at...
# https://craftbook.enginehub.org/en/latest//Usage
#
# NOTE! NOTHING IS ENABLED BY DEFAULT! ENABLE FEATURES TO USE THEM!


# List of mechanics and whether they are enabled or not
mechanics:
  boat:
    boat_decay: false
    boat_drops: false
    boat_exit_remover: false
    boat_remove_entities: false
    boat_speed_modifiers: false
    boat_uncrashable: false
    boat_water_place_only: false
    land_boats: false
  circuit:
    glowstone: false
    integrated_circuits: false
    jack_o_lantern: false
    jukebox: false
    netherrack: false
    pay: false
    pipes: false
  customisation:
    cauldron: false
    command_items: false
    custom_crafting: false
    custom_drops: false
    legacy_cauldron: false
  general:
    better_ai: false
    better_leads: false
    better_physics: false
    better_pistons: false
    better_plants: false
    bookcase: false
    bounce_blocks: false
    bridge: false
    chairs: false
    chunk_anchor: false
    command_signs: false
    cooking_pot: false
    dispenser_recipes: false
    door: false
    elevator: false
    gate: false
    head_drops: false
    hidden_switch: false
    light_switch: false
    map_changer: false
    marquee: false
    painting_switcher: false
    snow: false
    sponge: false
    teleporter: false
    toggle_area: false
    tree_lopper: false
    variables: true
    xp_storer: false
  minecart:
    minecart_booster: false
    minecart_collision_entry: false
    minecart_constant_speed: false
    minecart_decay: false
    minecart_deposit: false
    minecart_dispenser: false
    minecart_ejector: false
    minecart_elevator: false
    minecart_empty_slowdown: false
    minecart_exit_remover: false
    minecart_fall_modifier: false
    minecart_item_pickup: false
    minecart_max_speed: false
    minecart_messenger: false
    minecart_mob_blocker: false
    minecart_more_rails: false
    minecart_no_collide: false
    minecart_place_anywhere: false
    minecart_rail_placer: false
    minecart_remove_entities: false
    minecart_reverser: false
    minecart_sorter: false
    minecart_speed_modifiers: false
    minecart_station: false
    minecart_teleporter: false
    minecart_temporary_cart: false
    minecart_vision_steering: false
  tool:
    ammeter: false
    light_stone: false
    sign_copier: false

# WARNING! Changing this can result in all ST mechanics acting very weirdly, only change this if you know what you are doing!
st-think-ticks: 2

# Causes many mechanics to require sufficient blocks to function, for example gates, bridges and doors.
safe-destruction: true

# If on, OP's will not default to have access to everything.
no-op-permissions: false

# Allows redstone not directly facing a mechanism to trigger said mechanism.
indirect-redstone: false

# Rounds all distance equations to the block grid.
use-block-distance: false

# Checks to see if WorldGuard allows building/using in the area when activating mechanics.
check-worldguard-flags: true

# Use advanced methods to detect if a player can build or not. Use this if you use region protections other than WorldGuard, or experience issues with WorldGuard protection. This can add extra entries to Block Logging plugins when a mechanic is broken/placed.
advanced-block-checks: true

# In conjunction with advanced-block-checks, this option adds a few extra checks if you are experiencing compatibility issues with certain plugins that stop breaks/places/interacts.
pedantic-block-checks: false

# Make sure a player can only press signs so often.
sign-click-timeout: 10

# The default language for CraftBook. Note: This language needs to be in the 'languages' field for this to work.
language: en_US

# A list of languages supported by craftbook, if a user requests a language not listed... They will see default.
languages:
  - en_US

# If enabled, CraftBook will scan messages sent to players for localizable text, instead of just checking if the entire message is localizable.
scan-text-for-localization: false

# Enable a mode that will print extra debug information to the console.
debug-mode: false

# Causes all debug mode output to be logged into a file. This file is reset every startup (And every /cb reload).
debug-mode-file-logging: false

# Enable certain debug types when debug mode is enabled.
debug-flags: []

# Show messages when a player does not have permission to do something.
show-permission-messages: true

# PersistentStorage stores data that can be accessed across server restart. Method of PersistentStorage storage (Note: DUMMY is practically off, and may cause issues). Can currently be any of the following: YAML, DUMMY, SQLite
persistent-storage-type: YAML

# Causes mechanics to attempt to convert names to use CBIDs. This can and should be disabled after you believe your servers transition to UUIDs v Names is complete.
convert-names-to-cbids: false
